### PR TITLE
Use getModule() instead Module::getInstance()

### PR DESCRIPTION
**Pull request by ilgiz-badamshin**

### CODE REVIEW

**Comment by giannisdag** [comment]
I also agree that this is required, but it is better to use 
`$module = \Yii::$app->controller->module;`
because the proposed solution getModule assumes that the user uses a specific name for the module which is not always true.

**Comment by moltam** [comment]
Even better solution: `$this->controller->module`.

**Comment by ilgiz-badamshin** [comment]
Fixed it. But `Yii::$app->getModule('translatemanager')` is still used 8 times.

**Comment by moltam** [comment]
Is there a better way to access a module when not in a controller context (for example in a widget, or component)? I am not aware of it. I don't think we can remove all of the occurrences.

**Comment by ilgiz-badamshin** [comment]
I think we can use `Yii::$app->controller->module`.

**Comment by insane-dev** [comment]
May be use trait for that?
e.g.

```php
namespace lajax\translatemanager\traits;

use Yii;
use lajax\translatemanager\Module;

trait ModuleGetterTrait
{
    private $_module;

    public function getModule()
    {
        if ($this->_module === null) {
            $this->_module = Module::getInstance() ?: Yii::$app->getModule('translatemanager');
        }

        return $this->_module;
    }
}
```

And then when you want to give developers ability to change the name of the module in app config, you need to change only one method in one trait that is used all over the module.

Other ideas:
1. When user changes module name in app config, then advice him from module docs to set new module name in `Application::$params` property, and check that property in trait.
2. You can check context in trait: 
```php
if (property_exists($this, 'controller')) {
    $this->_module = $this->controller->module;
}

```

**Comment by lajax** [comment]
Thanks!

**Pull request merged**
